.TH INFAMOUS-RULES 1 "Jan, 17 2021"
.SH NAME
infamous-rules \- This program is less necessary as the new GUI shows
the first 20 states of the cells.
.SH USAGE

infamous-rules <rule number> <initial condition>

.SH DESCRIPTION
This program is less necessary as the new GUI shows the first 20 states
of the cells. 
.PP
The source is still there and compiles easily with a direct call to gcc.
This visualizes cell automata on a torus. Run it by opening a terminal run 
.PP
$ infamous-rule <rule number> <initial condition>
.PP    
The least significant digit corresponds to the first harmonic
.SH SEE ALSO
https://github.com/ssj71/infamousPlugins
.PP
.SH AUTHOR
This simple manual was created by Fernando Toledo <ragnarok@docksud.com.ar>
